import type { Metadata } from "next";
import "./globals.css";
import { Quicksand } from "next/font/google";
import { FavoritesProvider } from "./context/favoritesContext";

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Klein Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FavoritesProvider>
      <html lang="en">
        <body
          className={`${quicksand.variable} antialiased bg-custom-pattern bg-fixed bg-repeat bg-center bg-contain relative`}
        >
          <div className="absolute inset-0 bg-black bg-opacity-85"></div>
          <div className="relative z-10">{children}</div>
        </body>
      </html>
    </FavoritesProvider>

  );
}
